name: Push Priority Relations to S3

on:
  push:
    branches: [ "main" ]

jobs:
  push-relations:
    name: Push Priority Relations
    runs-on: ubuntu-latest
    steps:
      - name: Configure prod aws credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
        with:
          # unsafe! these are long lived static keys manually configured in github secrets!
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::1234:role/the-role-that-lets-us-use-s3
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-duration-seconds: 900
          aws-region: ${{ env.AWS_REGION }}

      - name: Push relations JSON to prod S3
        run: aws s3 cp relations.json s3://production-data/
